knpu_oauth2_client:
  clients:
    # will create service: "knpu.oauth2.client.github"
    # an instance of: KnpU\OAuth2ClientBundle\Client\Provider\GithubClient
    github:
      type: github
      # add and configure client_id and client_secret in parameters.yml
      client_id: '%app.github.client_id%'
      client_secret: '%app.github.client_secret%'
      # a route name you'll create
      redirect_route: login_check
      redirect_params: {}
      # whether to check OAuth2 "state": defaults to true
      # use_state: true
