version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8000:80"
    links:
      - phpfpm

  phpfpm:
    build: docker/phpfpm
    container_name: phpfpm
    hostname: phpfpm
    restart: always
    working_dir: /application
    environment:
      - APP_ENV=prod
      - APP_SECRET=10e4a9cbfdccac96e78ac7351e569287
      - GITHUB_REPO_USER=symfony
      - GITHUB_REPO_NAME=symfony
      - GITHUB_CLIENT_ID=582e56666e86509fc357
      - GITHUB_CLIENT_SECRET=bc7981abc6bbd84a49646d37a35dc1f469935cc2
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
    volumes:
      - .:/application
    links:
      - memcached

  memcached:
    image: memcached:latest
    container_name: memcached
    hostname: memcached
    restart: always
