parameters:
  app.github.client_id: '%env(GITHUB_CLIENT_ID)%'
  app.github.client_secret: '%env(GITHUB_CLIENT_SECRET)%'
  app.github.repo_user: '%env(GITHUB_REPO_USER)%'
  app.github.repo_name: '%env(GITHUB_REPO_NAME)%'
  app.memcached.host: '%env(MEMCACHED_HOST)%'
  app.memcached.port: '%env(MEMCACHED_PORT)%'
  locale: 'en'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  # some custom services

  Knp\Bundle\PaginatorBundle\Helper\Processor:
    class: '%knp_paginator.helper.processor.class%'
    arguments:
      - '@router'
      - '@translator'

  Knp\Component\Pager\Paginator:
    class: '%knp_paginator.class%'
    arguments:
      - '@event_dispatcher'

  App\Github\Client:
    arguments:
      $repoUser: '%app.github.repo_user%'
      $repoName: '%app.github.repo_name%'

  cache.adapter.memcached:
    class: Memcached
    calls:
      - [ addServer, [ '%app.memcached.host%', '%app.memcached.port%' ]]

  Cache\Adapter\Memcached\MemcachedCachePool:
    class: 'Cache\Adapter\Memcached\MemcachedCachePool'
    arguments:
      - '@cache.adapter.memcached'

  Github\Client:
    class: 'Github\Client'
    calls:
      - [ addCache, [ '@Cache\Adapter\Memcached\MemcachedCachePool' ]]
